require("juanmo.plugins")
require("juanmo.base")
require("juanmo.highlights")
require("juanmo.maps")
require("juanmo.macos")
require("juanmo.lsp.mason")
require("juanmo.lsp.lspsaga")
require("juanmo.lsp.lspconfig")
require("juanmo.lsp.null-ls")

