-- After you have what you want press C-Y and , at the same time
-- autocmd FileType html,css EmmetInstall
-- vim.g.user_emmet_leader_key='<leader>'

vim.g.user_emmet_mode='a'
vim.g.user_emmet_expandabbr_key = '<C-l>,'
vim.g.user_emmet_expandword_key = '<C-l>;'
vim.g.user_emmet_update_tag = '<C-l>u'
vim.g.user_emmet_balancetaginward_key = '<C-l>d'
vim.g.user_emmet_balancetagoutward_key = '<C-l>D'
vim.g.user_emmet_next_key = '<C-l>n'
vim.g.user_emmet_prev_key = '<C-l>N'
vim.g.user_emmet_imagesize_key = '<C-l>i'
vim.g.user_emmet_togglecomment_key = '<C-l>/'
vim.g.user_emmet_splitjointag_key = '<C-l>j'
vim.g.user_emmet_removetag_key = '<C-l>k'
vim.g.user_emmet_anchorizeurl_key = '<C-l>a'
vim.g.user_emmet_anchorizesummary_key = '<C-l>A'
vim.g.user_emmet_mergelines_key = '<C-l>m'
vim.g.user_emmet_codepretty_key = '<C-l>c'
