-- General mappings
require('plugins')
require('colorscheme')
require('keymappings')
require('settings')

-- Plugins
require('nv-autopairs')
require('nv-colorizer')
require('nv-emmet')
require('nv-comment')
require('nv-compe')
require('nv-gitsigns')
require('nv-telescope')
require('nv-treesitter')
require('nv-utils')

-- LSP
require('lsp')
require('lsp.bash-ls')
require('lsp.css-ls')
require('lsp.docker-ls')
require('lsp.efm-general-ls')
require('lsp.graphql-ls')
require('lsp.html-ls')
require('lsp.js-ts-ls')
require('lsp.json-ls')
require('lsp.lua-ls')
require('lsp.vim-ls')
require('lsp.virtual_text')
require('lsp.yaml-ls')
